browser = "firefox"
link = "https://accounts.google.com/signin/v2/identifier?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dde%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&hl=de&ec=65620&flowName=GlifWebSignIn&flowEntry=ServiceLogin"
mail = "<email>"
password = "<password>"
path = "<path>"
video = "<name>"
description = "<description>#shorts"
